# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: hsbc-backend-app-naz

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  stage: dev
  region: us-east-1

  # you can define service wide environment variables here
  environment:
    GITHUB_WEBHOOK_SECRET: cpsc319
    GITHUB_AUTHENTICATION_TOKEN: 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

  # you can add statements to the Lambda function's IAM Role here
  # iamRoleStatements:

functions:
  webhook:
    handler: functions/webhook.webhook
    events:
      - http:
          path: /webhook
          method: post
          cors: true
  users:
    handler: functions/routes/users.handler
    events:
      - http:
          path: /users
          method: ANY
      - http:
          path: /users/{proxy+}
          method: ANY
  violations:
    handler: functions/routes/violations.handler
    events:
      - http:
          path: /violations
          method: ANY
      - http:
          path: /violations/{proxy+}
          method: ANY
  emailSender:
    handler: functions/emailSender.handler
